
{{
    config(
        tags=['stage', 'жуфвр_1с']
    )
}}

SELECT
    recsource,
    loadts,
    hkcode,
    hk_dv_hub_fact_work,
	bk_работа_uuid,
	hdiff_dv_msat_norm_workload,
	период,
	рассчетный_объем,
	трудоемкость_нормативная,
	трудоемкость_фактическая,
	наемный_ресурс,
	ключевой_ресурс_value,
	ключевой_ресурс_code,
	ключевой_ресурс_name,
	несколько_ключевых_ресурсов,
	жуфвр,
	ключ_документа_ресурс,
	структура_работ_value,
	структура_работ_codе,
	структура_работ_name,
	ресурс_spider_value,
	ресурс_spider_codе,
	ресурс_spider_name,
	аналитика_value,
	аналитика_codе,
	аналитика_name
FROM (
    SELECT
        recsource,
        loadts,
        'default',
        digest('default' || '|' || LOWER(TRIM(COALESCE("Регистратор"::varchar, '-1')::varchar)), 'sha1') as hk_dv_hub_fact_work,
	LOWER(TRIM(COALESCE("Регистратор"::varchar, '-1')::varchar)),
	digest(TRIM(COALESCE("Период"::varchar, 'N\A')) || '|' || TRIM(COALESCE("РассчетныйОбъем"::varchar, 'N\A')) || '|' || TRIM(COALESCE("ТрудоемкостьНормативная"::varchar, 'N\A')) || '|' || TRIM(COALESCE("ТрудоемкостьФактическая"::varchar, 'N\A')) || '|' || TRIM(COALESCE("НаемныйРесурс"::varchar, 'N\A')) || '|' || TRIM(COALESCE("КлючевойРесурс_value"::varchar, 'N\A')) || '|' || TRIM(COALESCE("КлючевойРесурс_codе"::varchar, 'N\A')) || '|' || TRIM(COALESCE("КлючевойРесурс_name"::varchar, 'N\A')) || '|' || TRIM(COALESCE("НесколькоКлючевыхРесурсов"::varchar, 'N\A')) || '|' || TRIM(COALESCE("ЖУФВР"::varchar, 'N\A')) || '|' || TRIM(COALESCE("КлючДокументаРесурс"::varchar, 'N\A')) || '|' || TRIM(COALESCE("СтруктураРабот_value"::varchar, 'N\A')) || '|' || TRIM(COALESCE("СтруктураРабот_codе"::varchar, 'N\A')) || '|' || TRIM(COALESCE("СтруктураРабот_name"::varchar, 'N\A')) || '|' || TRIM(COALESCE("РесурсSpider_value"::varchar, 'N\A')) || '|' || TRIM(COALESCE("РесурсSpider_codе"::varchar, 'N\A')) || '|' || TRIM(COALESCE("РесурсSpider_name"::varchar, 'N\A')) || '|' || TRIM(COALESCE("Аналитика_value"::varchar, 'N\A')) || '|' || TRIM(COALESCE("Аналитика_codе"::varchar, 'N\A')) || '|' || TRIM(COALESCE("Аналитика_name"::varchar, 'N\A')), 'sha1') as hdiff_dv_msat_norm_workload,
	"Период"::timestamptz,
	"РассчетныйОбъем"::numeric,
	"ТрудоемкостьНормативная"::numeric,
	"ТрудоемкостьФактическая"::numeric,
	"НаемныйРесурс"::bool,
	"КлючевойРесурс_value"::uuid,
	"КлючевойРесурс_codе"::varchar,
	"КлючевойРесурс_name"::varchar,
	"НесколькоКлючевыхРесурсов"::bool,
	"ЖУФВР"::uuid,
	"КлючДокументаРесурс"::uuid,
	"СтруктураРабот_value"::uuid,
	"СтруктураРабот_codе"::varchar,
	"СтруктураРабот_name"::varchar,
	"РесурсSpider_value"::uuid,
	"РесурсSpider_codе"::varchar,
	"РесурсSpider_name"::varchar,
	"Аналитика_value"::uuid,
	"Аналитика_codе"::varchar,
	"Аналитика_name"::varchar
    FROM 
        {{ source('public', 'src_norm_workload') }}
) AS tmp (recsource, loadts, hkcode, hk_dv_hub_fact_work,
	bk_работа_uuid,
	hdiff_dv_msat_norm_workload,
	период,
	рассчетный_объем,
	трудоемкость_нормативная,
	трудоемкость_фактическая,
	наемный_ресурс,
	ключевой_ресурс_value,
	ключевой_ресурс_code,
	ключевой_ресурс_name,
	несколько_ключевых_ресурсов,
	жуфвр,
	ключ_документа_ресурс,
	структура_работ_value,
	структура_работ_codе,
	структура_работ_name,
	ресурс_spider_value,
	ресурс_spider_codе,
	ресурс_spider_name,
	аналитика_value,
	аналитика_codе,
	аналитика_name)
